# Generated by Django 3.0.6 on 2020-05-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMaster',
            fields=[
                ('camId', models.CharField(max_length=50, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('Focal', models.FloatField(max_length=40, verbose_name='Focal Length')),
                ('Range', models.FloatField(max_length=40, verbose_name='Max Range of Camera')),
                ('Pixel', models.FloatField(max_length=40, verbose_name='Pixel width')),
                ('FPS', models.FloatField(max_length=40, verbose_name='FramePerSecond(low fps = slower speed)')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Incident_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CameraId', models.CharField(max_length=40, verbose_name='Camera ID')),
                ('Date_Time_frm', models.DateTimeField(verbose_name='Date Time From')),
                ('Date_Time_to', models.DateTimeField(verbose_name='Date Time To')),
                ('SDVideoPath', models.CharField(max_length=100, verbose_name='Video Path')),
                ('FMVideoPath', models.CharField(max_length=100, verbose_name='Video Path')),
                ('SocialDistance', models.CharField(max_length=40, verbose_name='Social Distance')),
                ('FaceMask', models.CharField(max_length=40, verbose_name='Face Mask')),
            ],
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('LocationId', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Location ID')),
                ('location_name', models.CharField(max_length=40, verbose_name='Location Name')),
                ('Layer', models.CharField(max_length=40, verbose_name='Layer Number')),
                ('ParentId', models.CharField(max_length=40, verbose_name='Parent ID')),
                ('IpAdd', models.CharField(max_length=40, verbose_name='Ip Address')),
                ('camid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='detect.CameraMaster')),
            ],
        ),
    ]
