# Generated by Django 3.0.6 on 2020-07-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramaster',
            name='camerapassword',
            field=models.CharField(default=1, max_length=50, verbose_name='Camera Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameramaster',
            name='camerausername',
            field=models.CharField(default=1, max_length=50, verbose_name='Camera Username'),
            preserve_default=False,
        ),
    ]
