# Generated by Django 3.0.6 on 2020-07-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20200703_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameramaster',
            name='camerapassword',
        ),
        migrations.RemoveField(
            model_name='cameramaster',
            name='camerausername',
        ),
        migrations.AddField(
            model_name='cameramaster',
            name='relay',
            field=models.CharField(default=1, max_length=100, verbose_name='Relay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='locationpassword',
            field=models.CharField(default=1, max_length=500, verbose_name='Location Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='locationusername',
            field=models.CharField(default=1, max_length=50, verbose_name='Location Username'),
            preserve_default=False,
        ),
    ]
