# Generated by Django 3.0.6 on 2020-07-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_auto_20200706_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmaster',
            name='bottomleft',
            field=models.CharField(default=0, max_length=40, verbose_name='Bottom Left'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='bottomright',
            field=models.CharField(default=0, max_length=40, verbose_name='Bottom Right'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='horizontal',
            field=models.CharField(default=0, max_length=40, verbose_name='horizontal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='mid',
            field=models.CharField(default=0, max_length=40, verbose_name='mid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='topleft',
            field=models.CharField(default=0, max_length=40, verbose_name='Top Left'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='topright',
            field=models.CharField(default=0, max_length=40, verbose_name='Top Right'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='vertical',
            field=models.CharField(default=0, max_length=40, verbose_name='Vertical'),
            preserve_default=False,
        ),
    ]
